export type Product = {
  slug: string;
  className: string;
  name: string;
  nameHi: string;
  type: string;
  typeHi: string;
  image: string;
  pack: string;
  packHi: string;
  note: string;
  noteHi: string;
  overview: string;
  overviewHi: string;
  benefits: string[];
  benefitsHi: string[];
  suitable: string;
  suitableHi: string;
  usage?: string[];
  usageHi?: string[];
  catalogueUsage?: string[];
  catalogueUsageHi?: string[];
};

export const standardUse = {
  en: [
    'Read the product label completely before use.',
    'Use only at the crop stage, dose and application method recommended on the pack or by a qualified crop advisor.',
    'Keep the pack sealed, dry and away from direct sunlight after use.',
  ],
  hi: [
    'उपयोग से पहले उत्पाद के लेबल को ध्यान से पढ़ें।',
    'उत्पाद का उपयोग केवल पैक पर दिए गए फसल चरण, मात्रा और विधि के अनुसार या योग्य कृषि सलाहकार की सलाह से करें।',
    'उपयोग के बाद पैक को बंद, सूखी जगह और सीधी धूप से दूर रखें।',
  ],
};

export const products: Product[] = [
  {
    slug: 'super-calcium-gold', className: 'calcium-gold', name: 'Super Calcium Gold', nameHi: 'सुपर कैल्शियम गोल्ड',
    type: 'Calcium, magnesium & nutrient elements', typeHi: 'कैल्शियम, मैग्नीशियम एवं पोषक तत्व',
    image: '/products/super-calcium-gold.png', pack: '30 kg pack', packHi: '30 किग्रा पैक',
    note: 'Better growth, stronger crops', noteHi: 'बेहतर वृद्धि, मजबूत फसल',
    overview: 'A calcium, magnesium and nutrient-element product presented for stronger crop growth.',
    overviewHi: 'कैल्शियम, मैग्नीशियम और पोषक तत्वों से युक्त उत्पाद, जो बेहतर वृद्धि और मजबूत फसल के लिए प्रस्तुत किया गया है।',
    benefits: ['Calcium, magnesium and nutrient elements', 'Better growth', 'Stronger crops'],
    benefitsHi: ['कैल्शियम, मैग्नीशियम एवं पोषक तत्व', 'बेहतर वृद्धि', 'मजबूत फसल'],
    suitable: 'Use according to the product label and crop-advisor guidance.', suitableHi: 'पैक के लेबल और कृषि सलाहकार की सलाह के अनुसार उपयोग करें।',
  },
  {
    slug: 'gipl-24-karat', className: 'gipl', name: 'GIPL 24 Karat', nameHi: 'जीआईपीएल 24 कैरट',
    type: 'Gibberellic Acid 0.001% SL · Plant growth regulator', typeHi: 'जिबरेलिक एसिड 0.001% एसएल · पादप वृद्धि नियामक',
    image: '/products/gipl-24-karat.jpeg', pack: '100 ml', packHi: '100 मि.ली.',
    note: 'Plant growth regulator', noteHi: 'पादप वृद्धि नियामक',
    overview: 'A Gibberellic Acid 0.001% SL plant growth regulator in a 100 ml presentation.',
    overviewHi: '100 मि.ली. प्रस्तुति में जिबरेलिक एसिड 0.001% एसएल पादप वृद्धि नियामक।',
    benefits: ['Supports plant growth', 'Supports flowering and fruit setting', 'Supports fruit size, yield and quality'],
    benefitsHi: ['पौधों की वृद्धि में सहायक', 'फूल आने और फल सेटिंग में सहायक', 'फल के आकार, उपज और गुणवत्ता में सहायक'],
    suitable: 'Label-listed crops and crop programmes.', suitableHi: 'लेबल पर दी गई फसलों और फसल कार्यक्रमों के लिए।',
  },
  {
    slug: 'green-force', className: 'green-force', name: 'Green Phoss', nameHi: 'ग्रीन फॉस',
    type: 'Phosphate Rich Organic Manure', typeHi: 'फॉस्फेट समृद्ध जैविक खाद',
    image: '/products/green-force-packshot.png', pack: '50 kg pack', packHi: '50 किग्रा पैक',
    note: 'PROM · 8% P₂O₅', noteHi: 'पीआरओएम · 8% पी₂ओ₅',
    overview: 'Phosphate Rich Organic Manure presented for soil-nutrition programmes.',
    overviewHi: 'मिट्टी पोषण कार्यक्रमों के लिए प्रस्तुत फॉस्फेट समृद्ध जैविक खाद।',
    benefits: ['Phosphate-rich organic manure', 'Supports soil-nutrition programmes', '50 kg pack'],
    benefitsHi: ['फॉस्फेट समृद्ध जैविक खाद', 'मिट्टी पोषण कार्यक्रमों में सहायक', '50 किग्रा पैक'],
    suitable: 'Field and horticulture crop programmes, as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार खेत और बागवानी फसल कार्यक्रमों के लिए।',
  },
  {
    slug: 'super-baan', className: 'super-baan', name: 'सुपर बाण', nameHi: 'सुपर बाण',
    type: 'Super Prime Granular / Powder PROM', typeHi: 'सुपर प्राइम दानेदार / पाउडर पीआरओएम',
    image: '/products/super-baan-packshot.png', pack: '50 kg pack', packHi: '50 किग्रा पैक',
    note: 'Granular & powder', noteHi: 'दानेदार और पाउडर',
    overview: 'A Super Prime PROM offered in granular and powder forms.',
    overviewHi: 'दानेदार और पाउडर रूप में उपलब्ध सुपर प्राइम पीआरओएम।',
    benefits: ['Granular and powder formats', 'PROM crop-nutrition input', '50 kg pack'],
    benefitsHi: ['दानेदार और पाउडर रूप', 'पीआरओएम फसल-पोषण इनपुट', '50 किग्रा पैक'],
    suitable: 'Crop programmes as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार फसल कार्यक्रमों के लिए।',
  },
  {
    slug: 'dop-prom', className: 'dop-prom', name: 'D O P', nameHi: 'डी ओ पी',
    type: 'Phosphate Rich Organic Manure', typeHi: 'फॉस्फेट समृद्ध जैविक खाद',
    image: '/products/dop-prom-packshot.png', pack: '50 kg pack', packHi: '50 किग्रा पैक',
    note: 'PROM · 8% P₂O₅', noteHi: 'पीआरओएम · 8% पी₂ओ₅',
    overview: 'A Phosphate Rich Organic Manure in a 50 kg pack.',
    overviewHi: '50 किग्रा पैक में फॉस्फेट समृद्ध जैविक खाद।',
    benefits: ['PROM crop-nutrition input', 'Phosphate-rich formulation', '50 kg pack'],
    benefitsHi: ['पीआरओएम फसल-पोषण इनपुट', 'फॉस्फेट समृद्ध फॉर्मूलेशन', '50 किग्रा पैक'],
    suitable: 'Field and horticulture crop programmes, as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार खेत और बागवानी फसल कार्यक्रमों के लिए।',
  },
  {
    slug: 'potash', className: 'potash', name: 'Potash', nameHi: 'पोटाश',
    type: 'Dried Premium Molasses · K₂O 14.5%', typeHi: 'ड्राइड प्रीमियम मोलासेस · के₂ओ 14.5%',
    image: '/products/potash-packshot.png', pack: '50 kg pack', packHi: '50 किग्रा पैक',
    note: 'K₂O · 14.5%', noteHi: 'के₂ओ · 14.5%',
    overview: 'A dried premium molasses fertilizer for agricultural use, labelled K₂O 14.5%.',
    overviewHi: 'कृषि उपयोग के लिए ड्राइड प्रीमियम मोलासेस उर्वरक, जिस पर के₂ओ 14.5% अंकित है।',
    benefits: ['K₂O 14.5%', 'For agricultural use only', '50 kg pack'],
    benefitsHi: ['के₂ओ 14.5%', 'केवल कृषि उपयोग के लिए', '50 किग्रा पैक'],
    suitable: 'Agricultural crop programmes as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार कृषि फसल कार्यक्रमों के लिए।',
  },
  {
    slug: 'surya-super-zinc', className: 'surya-zinc', name: 'Surya Super Zinc', nameHi: 'सूर्या सुपर जिंक',
    type: 'Water-soluble fertilizer for foliar spray', typeHi: 'फोलियर स्प्रे के लिए जल में घुलनशील उर्वरक',
    image: '/products/surya-super-zinc.jpeg', pack: '250 g', packHi: '250 ग्राम',
    note: '100% water soluble', noteHi: '100% जल में घुलनशील',
    overview: 'A 100% water-soluble fertilizer presented for foliar spray.',
    overviewHi: 'फोलियर स्प्रे के लिए प्रस्तुत 100% जल में घुलनशील उर्वरक।',
    benefits: ['100% water soluble', 'For foliar spray', '250 g pack'],
    benefitsHi: ['100% जल में घुलनशील', 'फोलियर स्प्रे के लिए', '250 ग्राम पैक'],
    suitable: 'Foliar applications only as directed on the pack.', suitableHi: 'केवल पैक के निर्देशानुसार फोलियर उपयोग के लिए।',
  },
  {
    slug: 'zinc-super-gold', className: 'zinc-gold', name: 'Zinc Super Gold', nameHi: 'जिंक सुपर गोल्ड',
    type: 'Micronutrients + Sulphur · Zn 10%', typeHi: 'सूक्ष्म पोषक तत्व + सल्फर · जिंक 10%',
    image: '/products/zinc-super-gold.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'Micronutrients + sulphur', noteHi: 'सूक्ष्म पोषक तत्व + सल्फर',
    overview: 'A micronutrient and sulphur blend shown with zinc, iron, manganese, copper and boron on the supplied product pack.',
    overviewHi: 'उपलब्ध पैक जानकारी के अनुसार जिंक, आयरन, मैंगनीज, कॉपर और बोरॉन युक्त सूक्ष्म पोषक व सल्फर मिश्रण।',
    benefits: ['Complete micronutrient support', 'Supports root and leaf development', 'Supports crop quality and yield'],
    benefitsHi: ['समग्र सूक्ष्म पोषक सहयोग', 'जड़ और पत्ती विकास में सहायक', 'फसल की गुणवत्ता व उपज में सहायक'],
    suitable: 'Field, horticulture and flower crop programmes, as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार खेत, बागवानी और फूल फसल कार्यक्रमों के लिए।',
    usage: ['For soil use, mix 5-10 kg per acre as shown on the pack.', 'Apply according to the crop stage and field requirement.', 'Confirm the final dose with the product label or a qualified crop advisor.'],
    usageHi: ['पैक के अनुसार मृदा उपयोग हेतु 5-10 किग्रा प्रति एकड़ मिलाएँ।', 'फसल की अवस्था और खेत की जरूरत के अनुसार उपयोग करें।', 'अंतिम मात्रा के लिए लेबल या योग्य कृषि सलाहकार की सलाह लें।'],
    catalogueUsage: ['Soil: 5-10 kg per acre', 'Use by crop stage and need', 'Final dose: label / advisor'],
    catalogueUsageHi: ['मृदा: 5-10 किग्रा प्रति एकड़', 'फसल अवस्था के अनुसार उपयोग', 'अंतिम मात्रा: लेबल / सलाहकार'],
  },
  {
    slug: 'mono-zinc', className: 'mono-zinc', name: 'Mono Zinc', nameHi: 'मोनो जिंक',
    type: 'Zinc Sulphate Monohydrate · Zn 33% min · S 15% min', typeHi: 'जिंक सल्फेट मोनोहाइड्रेट · जिंक 33% न्यूनतम · सल्फर 15% न्यूनतम',
    image: '/products/mono-zinc.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'Zinc sulphate monohydrate', noteHi: 'जिंक सल्फेट मोनोहाइड्रेट',
    overview: 'An agriculture-grade Zinc Sulphate Monohydrate micronutrient fertilizer with Zn 33% minimum and S 15% minimum.',
    overviewHi: 'जिंक 33% न्यूनतम और सल्फर 15% न्यूनतम वाला कृषि-ग्रेड जिंक सल्फेट मोनोहाइड्रेट सूक्ष्म पोषक उर्वरक।',
    benefits: ['Helps correct zinc deficiency', 'Supports greener, healthier leaves', 'Supports flowering and fruit setting'],
    benefitsHi: ['जिंक की कमी दूर करने में सहायक', 'हरी व स्वस्थ पत्तियों में सहायक', 'फूल व फल सेटिंग में सहायक'],
    suitable: 'Wheat, paddy, maize, sugarcane, pulses, oilseeds, vegetables and horticulture crops.', suitableHi: 'गेहूं, धान, मक्का, गन्ना, दलहन, तिलहन, सब्जियां और बागवानी फसलें।',
    usage: ['Use in soil according to the crop and zinc-deficiency condition.', 'For foliar use, dissolve 2-3 g per litre of water as shown on the pack.', 'Use the final dose only as directed on the label or by a qualified crop advisor.'],
    usageHi: ['फसल और जिंक की कमी की स्थिति के अनुसार मृदा में उपयोग करें।', 'फोलियर उपयोग हेतु पैक के अनुसार 2-3 ग्राम प्रति लीटर पानी में घोलें।', 'अंतिम मात्रा लेबल या योग्य कृषि सलाहकार की सलाह के अनुसार ही रखें।'],
    catalogueUsage: ['Soil: as per crop need', 'Foliar: 2-3 g per litre', 'Final dose: label / advisor'],
    catalogueUsageHi: ['मृदा: फसल जरूरत के अनुसार', 'फोलियर: 2-3 ग्राम प्रति लीटर', 'अंतिम मात्रा: लेबल / सलाहकार'],
  },
  {
    slug: 'magnesium-gold', className: 'magnesium-gold', name: 'Magnesium Gold', nameHi: 'मैग्नीशियम गोल्ड',
    type: 'Magnesium 9.5% · Sulphate 12%', typeHi: 'मैग्नीशियम 9.5% · सल्फेट 12%',
    image: '/products/magnesium-gold.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'Magnesium + sulphate', noteHi: 'मैग्नीशियम + सल्फेट',
    overview: 'A magnesium and sulphate product with Magnesium (as Mg) 9.5% and Sulphate (as S) 12.0% shown on the supplied pack.',
    overviewHi: 'उपलब्ध पैक जानकारी के अनुसार मैग्नीशियम (एमजी) 9.5% और सल्फेट (एस) 12.0% युक्त उत्पाद।',
    benefits: ['Helps correct magnesium deficiency', 'Supports chlorophyll and photosynthesis', 'Supports crop quality and yield'],
    benefitsHi: ['मैग्नीशियम की कमी दूर करने में सहायक', 'क्लोरोफिल व प्रकाश संश्लेषण में सहायक', 'फसल की गुणवत्ता व उपज में सहायक'],
    suitable: 'Wheat, paddy, maize, sugarcane, pulses, oilseeds, vegetables and horticulture crops.', suitableHi: 'गेहूं, धान, मक्का, गन्ना, दलहन, तिलहन, सब्जियां और बागवानी फसलें।',
    usage: ['For soil use, apply 5-10 kg per acre according to crop need.', 'For foliar use, dissolve 2-3 g per litre of water.', 'Take crop-specific guidance from the label or a qualified advisor before use.'],
    usageHi: ['मृदा उपयोग हेतु फसल की जरूरत के अनुसार 5-10 किग्रा प्रति एकड़ उपयोग करें।', 'फोलियर उपयोग हेतु 2-3 ग्राम प्रति लीटर पानी में घोलें।', 'उपयोग से पहले लेबल या योग्य कृषि सलाहकार से फसल-विशिष्ट सलाह लें।'],
    catalogueUsage: ['Soil: 5-10 kg per acre', 'Foliar: 2-3 g per litre', 'Follow label / advisor guidance'],
    catalogueUsageHi: ['मृदा: 5-10 किग्रा प्रति एकड़', 'फोलियर: 2-3 ग्राम प्रति लीटर', 'लेबल / सलाहकार की सलाह मानें'],
  },
  {
    slug: 'fertile-blossom-high-zinc', className: 'blossom-zinc', name: 'Fasal Balwan High Zinc', nameHi: 'फसल बलवान हाई जिंक',
    type: 'Micronutrients + Sulphur · Zn 6%', typeHi: 'सूक्ष्म पोषक तत्व + सल्फर · जिंक 6%',
    image: '/products/fertile-blossom-high-zinc.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'High-zinc micronutrient blend', noteHi: 'हाई जिंक सूक्ष्म पोषक मिश्रण',
    overview: 'A micronutrient and sulphur blend with zinc, iron, manganese, copper and boron shown on the supplied Fasal Balwan High Zinc pack.',
    overviewHi: 'उपलब्ध फसल बलवान हाई जिंक पैक पर अंकित जिंक, आयरन, मैंगनीज, कॉपर और बोरॉन युक्त सूक्ष्म पोषक व सल्फर मिश्रण।',
    benefits: ['Complete micronutrient support', 'Supports root and plant development', 'Supports crop quality and yield'],
    benefitsHi: ['समग्र सूक्ष्म पोषक सहयोग', 'जड़ और पौध विकास में सहायक', 'फसल की गुणवत्ता व उपज में सहायक'],
    suitable: 'Field crops, vegetables, fruit crops and flowers, as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार खेत की फसलें, सब्जियां, फल और फूल फसलें।',
    usage: ['Mix 5-10 kg per acre with urea and apply as shown on the pack.', 'Adjust the application to the crop stage and field condition.', 'Follow the printed label and qualified crop-advisor guidance for the final dose.'],
    usageHi: ['पैक के अनुसार 5-10 किग्रा प्रति एकड़ यूरिया में मिलाकर उपयोग करें।', 'फसल की अवस्था और खेत की स्थिति के अनुसार उपयोग समायोजित करें।', 'अंतिम मात्रा के लिए छपे लेबल और योग्य कृषि सलाहकार की सलाह मानें।'],
    catalogueUsage: ['With urea: 5-10 kg per acre', 'Adjust for crop stage', 'Final dose: label / advisor'],
    catalogueUsageHi: ['यूरिया के साथ: 5-10 किग्रा प्रति एकड़', 'फसल अवस्था के अनुसार उपयोग', 'अंतिम मात्रा: लेबल / सलाहकार'],
  },
  {
    slug: 'boron-gold', className: 'boron-gold', name: 'Poshak', nameHi: 'पोषक',
    type: 'Sodium Tetraborate · Boron (B) 10.5% w/w min', typeHi: 'सोडियम टेट्राबोरेट · बोरॉन (बी) 10.5% w/w न्यूनतम',
    image: '/products/boron-gold.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'Micronutrient fertilizer', noteHi: 'सूक्ष्म पोषक उर्वरक',
    overview: 'A Sodium Tetraborate micronutrient fertilizer for soil application, with Boron (as B) 10.5% w/w minimum shown on the pack.',
    overviewHi: 'मृदा उपयोग के लिए सोडियम टेट्राबोरेट सूक्ष्म पोषक उर्वरक, जिसमें पैक के अनुसार बोरॉन (बी) 10.5% w/w न्यूनतम है।',
    benefits: ['Supports flowering and fruit development', 'Supports pollen, fruit set and seed formation', 'Supports fruit quality, size and yield'],
    benefitsHi: ['फूल व फल विकास में सहायक', 'परागण, फल सेटिंग और बीज निर्माण में सहायक', 'फल की गुणवत्ता, आकार व उपज में सहायक'],
    suitable: 'Field, vegetable, fruit and horticulture crop programmes, for soil use.', suitableHi: 'मृदा उपयोग हेतु खेत, सब्जी, फल और बागवानी फसल कार्यक्रमों के लिए।',
    usage: ['For soil application, use 3-6 kg per acre according to crop need.', 'For drip use, apply 1.5-3 kg per acre as shown on the pack.', 'Take final crop-specific guidance from the printed label or a qualified advisor.'],
    usageHi: ['मृदा उपयोग हेतु फसल की जरूरत के अनुसार 3-6 किग्रा प्रति एकड़ प्रयोग करें।', 'ड्रिप उपयोग हेतु पैक के अनुसार 1.5-3 किग्रा प्रति एकड़ डालें।', 'अंतिम फसल-विशिष्ट सलाह लेबल या योग्य कृषि सलाहकार से लें।'],
    catalogueUsage: ['Soil: 3-6 kg per acre', 'Drip: 1.5-3 kg per acre', 'Final dose: label / advisor'],
    catalogueUsageHi: ['मृदा: 3-6 किग्रा प्रति एकड़', 'ड्रिप: 1.5-3 किग्रा प्रति एकड़', 'अंतिम मात्रा: लेबल / सलाहकार'],
  },
  {
    slug: 'micro-force', className: 'micro-force', name: 'Micro Ferrous', nameHi: 'माइक्रो फेरस',
    type: 'Ferrous Sulphate · Fe 19% · S 10.5%', typeHi: 'फेरस सल्फेट · आयरन 19% · सल्फर 10.5%',
    image: '/products/micro-force.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'Ferrous sulphate', noteHi: 'फेरस सल्फेट',
    overview: 'A Ferrous Sulphate micronutrient fertilizer with Fe 19% and S 10.5% shown on the supplied pack.',
    overviewHi: 'उपलब्ध पैक जानकारी के अनुसार आयरन 19% और सल्फर 10.5% युक्त फेरस सल्फेट सूक्ष्म पोषक उर्वरक।',
    benefits: ['Helps correct iron deficiency', 'Supports greener leaves and photosynthesis', 'Supports root strength and crop quality'],
    benefitsHi: ['आयरन की कमी दूर करने में सहायक', 'हरी पत्तियों व प्रकाश संश्लेषण में सहायक', 'जड़ों की मजबूती व फसल गुणवत्ता में सहायक'],
    suitable: 'Field crops, vegetables and horticulture programmes, as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार खेत की फसलें, सब्जियां और बागवानी कार्यक्रम।',
    usage: ['For soil application, use 3-5 kg per acre according to crop need.', 'For foliar use, dissolve 2.5-5 g per litre of water.', 'For drip use, apply 1-2 kg per acre; follow the label or a qualified advisor.'],
    usageHi: ['मृदा उपयोग हेतु फसल की जरूरत के अनुसार 3-5 किग्रा प्रति एकड़ प्रयोग करें।', 'फोलियर उपयोग हेतु 2.5-5 ग्राम प्रति लीटर पानी में घोलें।', 'ड्रिप उपयोग हेतु 1-2 किग्रा प्रति एकड़ डालें; लेबल या विशेषज्ञ की सलाह मानें।'],
    catalogueUsage: ['Soil: 3-5 kg per acre', 'Foliar: 2.5-5 g per litre', 'Drip: 1-2 kg per acre'],
    catalogueUsageHi: ['मृदा: 3-5 किग्रा प्रति एकड़', 'फोलियर: 2.5-5 ग्राम प्रति लीटर', 'ड्रिप: 1-2 किग्रा प्रति एकड़'],
  },
  {
    slug: 'black-gold', className: 'black-gold', name: 'Black Gold', nameHi: 'ब्लैक गोल्ड',
    type: 'Organic growth stimulator · Humic 98% w/w', typeHi: 'जैविक वृद्धि प्रवर्तक · ह्यूमिक 98% w/w',
    image: '/products/black-gold.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'Humic 98% w/w', noteHi: 'ह्यूमिक 98% w/w',
    overview: 'An organic growth stimulator with Potassium Humate 98% w/w and other growth enzymes 2% shown on the supplied pack.',
    overviewHi: 'उपलब्ध पैक जानकारी के अनुसार पोटैशियम ह्यूमेट 98% w/w और अन्य ग्रोथ एंजाइम 2% युक्त जैविक वृद्धि प्रवर्तक।',
    benefits: ['Supports soil structure and root growth', 'Supports nutrient uptake and plant development', 'Supports crop resilience, quality and yield'],
    benefitsHi: ['मिट्टी की संरचना व जड़ विकास में सहायक', 'पोषक तत्व अवशोषण व पौध विकास में सहायक', 'फसल सहनशीलता, गुणवत्ता व उपज में सहायक'],
    suitable: 'Field crops, vegetables and horticulture crops, as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार खेत की फसलें, सब्जियां और बागवानी फसलें।',
    usage: ['For soil use, apply 500 g to 1 kg per acre as shown on the pack.', 'For foliar or drip use, follow crop-specific advice from a qualified advisor.', 'Keep the pack sealed, dry and away from direct sunlight after use.'],
    usageHi: ['मृदा उपयोग हेतु पैक के अनुसार 500 ग्राम से 1 किग्रा प्रति एकड़ डालें।', 'फोलियर या ड्रिप उपयोग हेतु योग्य कृषि सलाहकार की फसल-विशिष्ट सलाह लें।', 'उपयोग के बाद पैक को बंद, सूखी जगह और सीधी धूप से दूर रखें।'],
    catalogueUsage: ['Soil: 500 g to 1 kg per acre', 'Foliar / drip: advisor guidance', 'Store sealed, dry and shaded'],
    catalogueUsageHi: ['मृदा: 500 ग्राम से 1 किग्रा प्रति एकड़', 'फोलियर / ड्रिप: सलाहकार की सलाह', 'पैक बंद, सूखा और छायादार रखें'],
  },
  {
    slug: 'bhumi-pakar', className: 'bhumihar', name: 'Boom Flower', nameHi: 'बूम फ्लावर',
    type: 'Nitro 35% + Humic Acid 15% + Amino Acid 10%', typeHi: 'नाइट्रो 35% + ह्यूमिक एसिड 15% + अमीनो एसिड 10%',
    image: '/products/bhumihar.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'Biostimulant', noteHi: 'बायोस्टिमुलेंट',
    overview: 'A biostimulant product with Nitro 35%, Humic Acid 15% and Amino Acid 10% shown on the supplied Boom Flower pack.',
    overviewHi: 'उपलब्ध बूम फ्लावर पैक पर अंकित नाइट्रो 35%, ह्यूमिक एसिड 15% और अमीनो एसिड 10% युक्त बायोस्टिमुलेंट उत्पाद।',
    benefits: ['Supports faster plant growth', 'Supports flowering and fruit development', 'Supports nutrient uptake and crop quality'],
    benefitsHi: ['तेज पौध वृद्धि में सहायक', 'फूल व फल विकास में सहायक', 'पोषक अवशोषण व फसल गुणवत्ता में सहायक'],
    suitable: 'Vegetables, fruit crops, flowers and horticulture crop programmes.', suitableHi: 'सब्जियां, फल फसलें, फूल और बागवानी फसल कार्यक्रम।',
    usage: ['For soil use, mix 3-4 kg per acre with manure or other fertilizer as shown on the pack.', 'At flowering and fruit stage, follow the pack guidance for application.', 'Keep the pack sealed, dry and away from direct sunlight after use.'],
    usageHi: ['मृदा उपयोग हेतु पैक के अनुसार गोबर खाद या अन्य उर्वरक के साथ 3-4 किग्रा प्रति एकड़ मिलाएँ।', 'फूल और फल अवस्था में पैक पर दी गई उपयोग विधि का पालन करें।', 'उपयोग के बाद पैक को बंद, सूखी जगह और सीधी धूप से दूर रखें।'],
    catalogueUsage: ['Soil: 3-4 kg per acre', 'Flower / fruit stage: pack guidance', 'Store sealed, dry and shaded'],
    catalogueUsageHi: ['मृदा: 3-4 किग्रा प्रति एकड़', 'फूल / फल अवस्था: पैक के अनुसार', 'पैक बंद, सूखा और छायादार रखें'],
  },
  {
    slug: 'haryali-gold', className: 'haryali-gold', name: 'Haryali Gold', nameHi: 'हरियाली गोल्ड',
    type: 'Chelated Iron as Fe-EDTA 12%', typeHi: 'फी-ईडीटीए 12% के रूप में चेलेटेड आयरन',
    image: '/products/haryali-gold.jpeg', pack: '1 kg pack', packHi: '1 किग्रा पैक',
    note: 'Chelated iron', noteHi: 'चेलेटेड आयरन',
    overview: 'A chelated iron micronutrient fertilizer with Fe-EDTA 12%, presented for drip and foliar application.',
    overviewHi: 'फी-ईडीटीए 12% वाला चेलेटेड आयरन सूक्ष्म पोषक उर्वरक, ड्रिप और फोलियर उपयोग के लिए प्रस्तुत।',
    benefits: ['Helps correct iron deficiency', 'Helps reduce leaf yellowing', 'Supports green leaves, quality and size'],
    benefitsHi: ['आयरन की कमी दूर करने में सहायक', 'पत्तियों का पीलापन कम करने में सहायक', 'हरी पत्तियों, गुणवत्ता व आकार में सहायक'],
    suitable: 'Drip and foliar application for crop programmes, as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार फसल कार्यक्रमों में ड्रिप और फोलियर उपयोग के लिए।',
    usage: ['For drip use, apply 4-5 kg per acre as shown on the pack.', 'For foliar use, dissolve 2-3 g per litre of water.', 'Use the final dose according to the label or a qualified crop advisor.'],
    usageHi: ['ड्रिप उपयोग हेतु पैक के अनुसार 4-5 किग्रा प्रति एकड़ डालें।', 'फोलियर उपयोग हेतु 2-3 ग्राम प्रति लीटर पानी में घोलें।', 'अंतिम मात्रा लेबल या योग्य कृषि सलाहकार की सलाह के अनुसार रखें।'],
    catalogueUsage: ['Drip: 4-5 kg per acre', 'Foliar: 2-3 g per litre', 'Final dose: label / advisor'],
    catalogueUsageHi: ['ड्रिप: 4-5 किग्रा प्रति एकड़', 'फोलियर: 2-3 ग्राम प्रति लीटर', 'अंतिम मात्रा: लेबल / सलाहकार'],
  },
  {
    slug: 'super-power-win', className: 'power-win', name: 'Super Power Win', nameHi: 'सुपर पावर विन',
    type: 'Plant Growth Promoter', typeHi: 'पादप वृद्धि प्रवर्तक',
    image: '/products/super-power-win.jpg', pack: '0.3 L × 10 pack', packHi: '0.3 ली. × 10 पैक',
    note: 'Healthy plant, better yield', noteHi: 'स्वस्थ पौधे, बेहतर उपज',
    overview: 'A plant growth promoter presented for healthy plants and better yield.',
    overviewHi: 'स्वस्थ पौधों और बेहतर उपज के लिए प्रस्तुत पादप वृद्धि प्रवर्तक।',
    benefits: ['Supports plant growth and development', 'Supports stronger roots', 'Supports flowers, fruits, yield and quality'],
    benefitsHi: ['पौधों की वृद्धि और विकास में सहायक', 'जड़ों को मजबूत बनाने में सहायक', 'फूल, फल, उपज और गुणवत्ता में सहायक'],
    suitable: 'All crops, as directed on the label.', suitableHi: 'लेबल के निर्देशानुसार सभी फसलों के लिए।',
  },
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
